### ISSUE TITLE
[Issue]: Docker - Install failure on first run

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rocPyDecode#27]
### Problem Description

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rocdecode
ERROR_CHECK failed with status:25600
CMake Error: The current CMakeCache.txt directory /root/rocPyDecode/build/CMakeCache.txt is different than the directory /home/kiriti/develop/rocPyDecode-kiriti/rocPyDecode/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/root/rocPyDecode/CMakeLists.txt" does not match the source "/home/kiriti/develop/rocPyDecode-kiriti/rocPyDecode/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Traceback (most recent call last):
  File "/root/rocPyDecode/setup.py", line 29, in <module>
    subprocess.check_call(cmake_args,cwd=os.getcwd())
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '.', '-B/root/rocPyDecode/build', '-H/root/rocPyDecode']' returned non-zero exit status 1.

To test rocPyDecode run the following command:
 python3 samples/videodecode.py -i data/videos/AMD_driving_virtual_20-H265.mp4 
```

### Operating System

ALL

### CPU

ALL

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.1.0

**Comment by ppanchad-amd** [comment]
@kiritigowda Closing ticket. Please re-open ticket if you are still seeing the issue after trying @essamROCm suggestion above. Thanks!
